import type { LLMGeneratorConfig } from "@/lib/llm-test-generator"
import { CLI } from "../cli"

export const config: LLMGeneratorConfig = {
  stimuli: {
    systemText:
      "You are a high school psychology teacher employed by the collegeboard to create stimuli for questions on the AP Psychology exam.",
    descriptions: {
      text: "Provide an fake situation related to psychological theories, studies, experiments, or concepts. This should be detailed enough to inform the subsequent questions.",
      attribution: "The author, organization, or source of the material.",
    },
  },
  mcqs: {
    systemText:
      "You are a high school psychology teacher employed by the collegeboard to create multiple choice questions for the AP Psychology exam.",
    descriptions: {
      question:
        "Develop a multiple choice question that tests understanding or application of psychological concepts related to the stimulus. Include one correct answer and several plausible distractors.",
    },
  },
  frqs: {
    systemText:
      "You are a high school psychology teacher employed by the collegeboard to create free response questions for the AP Psychology exam.",
    descriptions: {
      question:
        "Create a free response question that requires the definition of a specific psychological term and an explanation of how this term applies to the context provided in the stimulus. The response should demonstrate an understanding of both the definition and the application of the term in a relevant scenario.",
    },
  },
}

export const subjectName = "AP Psychology"

export const unitNames = [
  "Unit 1: Scientific Foundations of Psychology - Psychology, Science, Behavior, Mental Processes, Critical Thinking, Empirical Method, Positive Psychology, Structuralism, Functionalism, Natural Selection, Biological Approach, Neuroscience, Behavioral Approach, Psychodynamic Approach, Humanistic Approach, Cognitive Approach, Evolutionary Approach, Sociocultural Approach, Psychopathology, Physiological and Behavioral Neuroscience, Sensation and Perception, Learning Psychology, Cognitive Psychology, Developmental Psychology, Motivation and Emotion Psychology, Women and Gender Psychology, Personality Psychology, Social Psychology, Industrial and Organizational (I/O) Psychology, Clinical and Counseling Psychology, Health Psychology, Community Psychology, Environmental Psychology, Forensic Psychology, Sport Psychology, Cross-Cultural Psychology, Wilhelm (William) Wundt, William James, B.F. Skinner, Charles Darwin, Sigmund Freud, John B. Watson, Variable, Theory, Hypothesis, Operational Definition, Meta-Analysis, Descriptive Research, Case Study, Correlational Research, Third Variable Problem, Longitudinal Design, Experiment, Random Assignment, Independent Variable, Confederate, Dependent Variable, Experimental Group, Control Group, External Validity, Internal Validity, Experimenter Bias, Demand Characteristics, Research Participant Bias, Placebo Effect, Placebo, Double Blind Experiment, Population, Sample, Random Sample, Naturalistic Observation, Descriptive Statistics, Mean, Median, Mode, Range, Standard Deviation, Inferential Studies",
  "Unit 2: Biological Bases of Behavior - biological psychologists, neuron, dendrites, axon, myelin sheath, action potential, refractory period, threshold, all-or-nothing response, synapse, neurotransmitters, reuptake, endorphins, agonist, antagonists, nervous system, Central nervous system (CNS), Peripheral nervous system (PNS), nerves, sensory (afferent) neurons, motor (efferent) neurons, interneurons, somatic nervous system, autonomic nervous system, sympathetic nervous system, parasympathetic nervous system, reflexes, endocrine system, hormones, adrenal glands, pituitary gland, lesion, electroencephalogram (EEG), CT (computed tomography) scan, PET (positron emission tomography) scan, MRI (magnetic resonance imaging), fMRI (functional MRI), brainstem, medulla, pons, thalamus, reticular formation, cerebellum, limbic system, amygdala, hippocampus, hypothalamus, cerebral cortex, glial cells, frontal lobes, parietal lobes, occipital lobes, temporal lobes, motor cortex, somatosensory cortex, association areas, plasticity, neurogenesis, corpus callosum, split brain, consciousness, cognitive neuroscience, dual processing, behavior genetics, environment, chromosomes, DNA (deoxyribonucleic acid), genes, genome, identical twins (monozygotic), fraternal twins (dizygotic), molecular geneticists, heritability, interaction, epigenetics, evolutionary psychologists, natural selection, mutations",
  "Unit 3: Sensation and Perception - Biological Psychologists, Neuron, Dendrites, Soma (Cell Body), Axon, Myelin Sheath, Synapse, Resting State, Level of Excitation, Action Potential, Refractory Phase, Excitatory Neurotransmitter, Inhibitory Neurotransmitter, Serotonin, Dopamine, Acetylcholine, Norepinephrine (Noradrenalin), GABA, Endorphins, Glutamate, Afferent Neurons (Sensory Neurons), Interneuron, Efferent Neurons (Motor Neurons), Central Nervous System (CNS), Peripheral Nervous System (PNS), Somatic, Autonomic, Autonomic: Sympathetic, Autonomic: Parasympathetic, Wilder Penfield, Localization, Plasticity, Hindbrain, Medulla Oblongata, Pons, Cerebellum, Midbrain, Basal Ganglia, Nucleus Accumbens, Thalamus, Hypothalamus, Amygdala, Hippocampus, Limbic System, Cerebral Cortex/Cerebrum, Left Hemisphere, Right Hemisphere, Frontal Lobe, Parietal Lobe, Occipital Lobe, Temporal Lobe, Endocrine System, Adrenal Gland, Melatonin, Monozygotic, Dizygotic, Thomas Bouchard",
  "Unit 4: Learning - Associative Learning, Classical Conditioning, Learning, Behaviorism, Unconditioned Response, Unconditioned Stimulus, Conditioned Response, Conditioned Stimulus, Acquisition, Extinction, Spontaneous Recovery, Generalization, Discrimination, Operant Conditioning, Respondent Behavior, Operant Behavior, Law of Effect, Operant Chamber, Shaping, Reinforcer, Positive Reinforcement, Negative Reinforcement, Primary Reinforcer, Conditioned Reinforcer, Continuous Reinforcement, Partial Reinforcement, Fixed Ratio Schedule, Variable Ratio Schedule, Fixed Interval Schedule, Variable Interval Schedule, Punishment, Cognitive Map, Latent Learning, Intrinsic Motivation, Extrinsic Motivation, Observational Learning, Modeling, Mirror Neurons, Prosocial Behavior, Memory, Flashbulb Memory, Encoding, Storage, Retrieval, Sensory Memory, Short-Term Memory, Long-Term Memory, Working Memory, Automatic Processing, Effortful Processing, Rehearsal, Spacing Effect, Serial Position Effect, Visual Encoding, Acoustic Encoding, Semantic Encoding, Imagery, Mnemonics, Chunking, Iconic Memory, Echoic Memory, Long Term Potentiation, Amnesia, Implicit Memory, Explicit Memory, Hippocampus, Recall, Recognition, Relearning, Priming, Deja Vu, Mood-Congruent Memory, Proactive Interference, Retroactive Interference, Repression, Misinformation Effect, Source Amnesia.",
  "Unit 5: Cognitive Psychology - Memory, Encoding, Storage, Retrieval, Parallel Processing, Effortful Processing, Shallow Processing, Deep Processing, Hippocampus, Selective Attention, Automatic Processing, Overlearning, Rehearsal, Semantic Encoding, Mnemonic Effect, Method of Loci, Self-Reference Effect, Chunking, Basal Ganglia, Peg-Word System, Sensory Memory, Working Memory, Serial Position Effect, Context Effect, Mood-Congruent Memory, Testing Effect, Spacing Effect, Permastore Memory, State-Dependent Memory, Retroactive Interference, Proactive Interference, Repression, Anterograde Amnesia, Short-Term Memory, Retrograde Amnesia, Misinformation Effect, Source Amnesia, Déjà Vu, Reconsolidation, Long-Term Memory, Iconic Memory, Flashbulb Memory, Long-Term Potentiation (LTP), Echoic Memory, Implicit Memory, Explicit Memory, Episodic Memory, Recall, Recognition, Relearning, Priming, Semantic Memory, Cognitive Abilities, Convergent Thinking, Divergent Thinking, Overconfidence, Belief Perseverance, Framing, Concept, Morpheme, Phoneme, Syntax, Aphasia, Grammar, Linguistic Determinism, Algorithm, Linguistic Influence, Heuristic, Intuition, Representative Heuristic, Insight, Availability Heuristic, Mental Set, Confirmation Bias, Functional Fixedness, Prototype, Fixation, Intelligence, General Intelligence, Savant Syndrome, Factor Analysis, Grit, Emotional Intelligence, Achievement Test, Aptitude Test, Intelligence Test, Mental Age, Wechsler Adult Intelligence Scale (WAIS), Intelligence Quotient (IQ), Standardization, Reliability, Stanford Binet, Validity, Normal Curve, Predictive Validity, Content Validity, Cohort, Crystallized Intelligence, Flynn Effect, Fluid Intelligence",
  "Unit 6: Developmental Psychology - Learning, Habituation, Associative Learning, Classical Conditioning, Behaviorism, Unconditioned Response (UR), Unconditioned Stimulus (US), Conditioned Response (CR), Conditioned Stimulus (CS), Acquisition, Higher-Order Conditioning, Extinction, Spontaneous Recovery, Generalization, Discrimination, Learned Helplessness, Respondent Behavior, Operant Conditioning, Operant Behavior, Law of Effect, Operant Chamber, Shaping, Discriminative Stimulus, Reinforcer, Positive Reinforcement, Negative Reinforcement, Primary Reinforcer, Conditioned Reinforcer, Continuous Reinforcement, Partial (Intermittent) Reinforcement, Fixed-Ratio Schedule, Variable-Ratio Schedule, Fixed-Interval Schedule, Variable-Interval Schedule, Punishment, Cognitive Map, Latent Learning, Insight, Intrinsic Motivation, Extrinsic Motivation, Biofeedback, Observational Learning, Modeling, Mirror Neurons, Prosocial Behavior",
  "Unit 7: Motivation, Emotion, and Personality - Memory, Encoding, Storage, Retrieval, Sensory Memory, Short-Term Memory, Long-Term Memory, Working Memory, Parallel Processing, Automatic Processing, Effortful Processing, Rehearsal, Spacing Effect, Serial Position Effect, Visual Encoding, Acoustic Encoding, Semantic Encoding, Imagery, Mnemonics, Chunking, Iconic Memory, Echoic Memory, Long-Term Potentiation, Flashbulb Memory, Amnesia, Implicit Memory, Explicit Memory, Hippocampus, Recall, Recognition, Relearning, Priming, Deja Vu, Mood-Congruent Memory, Proactive Interference, Retroactive Interference, Repression, Misinformation Effect, Source Amnesia, Cognition, Concept, Prototype, Algorithm, Heuristic, Insight, Creativity, Confirmation Bias, Fixation, Mental Set, Functional Fixedness, Representativeness Heuristic, Availability Heuristic, Overconfidence, Belief Perseverance, Intuition, Framing, Language, Phoneme, Morpheme, Grammar, Semantics, Syntax, Babbling Stage, One-Word Stage, Two-Word Stage, Telegraphic Speech, Linguistic Determinism",
  "Unit 8: Clinical Psychology - Hallucinations, Delusions, Culture-Bound Syndromes, Dhat Syndrome, Medical Model, Biopsychosocial Model, Diathesis-Stress Model, Diathesis, Psychological Disorders, Unusualness, Social Deviance, Emotional Distress, Maladaptive Behaviors, Dangerousness, Faulty Perceptions or Interpretations of Reality, Anxiety Disorders, Phobias, Social Phobia, Specific Phobia, Acrophobia, Claustrophobia, Agoraphobia, Panic Disorder, Generalized Anxiety Disorder (GAD), Obsessive-Compulsive Disorder (OCD), Anxiety Sensitivity, Dissociative Disorders, Somatoform Disorders, Dissociative Identity Disorder (DID), Conversion Disorder, Hypochondriasis, Secondary Gain, Mood Disorders, Major Depressive Disorder, Seasonal Affective Disorder (SAD), Dysthymic Disorder, Bipolar Disorder, Manic Episodes, Cyclothymic Disorder, Learned Helplessness Model, Attributional Style, Depressive Attributional Style, Disinhibition Effect, Schizophrenia, Psychotic Disorder, Thought Disorder, Positive Symptoms, Negative Symptoms, Disorganized Type, Catatonic Type, Waxy Flexibility, Paranoid Type, Personality Disorders, Narcissistic Personality Disorder, Paranoid Personality Disorder, Schizoid Personality Disorder, Borderline Personality Disorder, Antisocial Personality Disorder (APD)",
  "Unit 9: Social Psychology - Social Psychology, Attribution Theory, Fundamental Attribution Error, Attitudes, Central Route Persuasion, Peripheral Route Persuasion, Foot-in-the-Door Phenomenon, Role, Cognitive Dissonance Theory, Conformity, Normative Social Influence, Informational Social Influence, Social Facilitation, Social Loafing, Deindividuation, Group Polarization, Groupthink, Culture, Norm, Personal Space, Prejudice, Stereotype, Discrimination, Ingroup, Outgroup, Ingroup Bias, Scapegoat Theory, Other-Race Effect, Just-World Phenomenon, Aggression, Frustration-Aggression Principle, Mere Exposure Effect, Passionate Love, Companion Love, Equity, Self-Disclosure, Altruism, Bystander Effect, Social Exchange Theory, Reciprocity Norm, Social-Responsibility Norm, Conflict, Social Trap, Mirror-Image Perceptions, Self-Fulfilling Prophecy, Superordinate Goals, GRIT",
]

export const cli = await CLI.create(subjectName, unitNames, config)