import type { LLMGeneratorConfig } from "@/lib/llm-test-generator"
import { CLI } from "../cli"

export const config: LLMGeneratorConfig = {
  stimuli: {
    systemText:
        "You are a high school geography teacher employed by the College Board to create stimuli for questions on the AP Human Geography exam.",
    descriptions: {
        text: "Provide a short, two sentence max, hypothetical situation related to geographic theories, historical development, urban planning, or human-environment interactions. This should be detailed enough to inform the subsequent questions. The scenario should focus on specific geographic principles, spatial relationships, or human activities.",
        attribution: "The author, organization, or source of the material.",
    },
  },
  mcqs: {
    systemText:
        "You are a high school geography teacher employed by the College Board to create multiple-choice questions for the AP Human Geography exam.",
    descriptions: {
        question:
            "Develop a multiple-choice question that tests students' understanding of the application of specific geographic concepts. The question should be assess the knowledge of geographic principles in relation to the hypothetical example. Include one correct answer and several plausible distractors that reflect common misconceptions or errors. Subsequent questions should not merely reword previous questions. New concepts should be introduced.",
    },
  },
  frqs: {
    systemText:
        "You are a high school geography teacher employed by the College Board to create free response questions for the AP Human Geography exam.",
    descriptions: {
        question:
            "Develop a free response question that requires students to explain a geographic concept in detail, including defining specific terms and illustrating the concept with a relevant example. The response should demonstrate a comprehensive understanding of both the definition and practical application of the concept in a geographic context. Ensure the question allows for an in-depth explanation and analysis of geographic principles or processes.",
    },
  },
}

export const subjectName = "AP Human Geography"

export const unitNames = [
  "Unit 1: Thinking Geographically - maps, scale, projection, GIS, GPS, remote sensing, location, place, region, space, pattern, spatial analysis, human-environment interaction, absolute location, relative location, site, situation, toponyms, cultural landscape, mental maps, map types, thematic maps, choropleth maps, isoline maps, dot distribution maps, proportional symbol maps, cartogram, spatial perspective, global positioning system, geocaching, map scale, time zones, map projection, Robinson projection, Mercator projection, Peters projection, spatial distribution, spatial interaction, distance decay, friction of distance, space-time compression, cultural ecology, environmental determinism, possibilism, geographic scale, qualitative data, quantitative data",
  "Unit 2: Population and Migration - demography, population density, population distribution, population pyramid, carrying capacity, fertility rate, mortality rate, natural increase rate (NIR), demographic transition model (DTM), epidemiologic transition, Malthusian theory, migration, push factors, pull factors, refugees, internally displaced persons (IDPs), asylum seekers, voluntary migration, forced migration, chain migration, migration transition model, brain drain, remittances, population growth, overpopulation, zero population growth (ZPG), dependency ratio, age-sex structure, census, doubling time, infant mortality rate, life expectancy, total fertility rate (TFR), graying population, anti-natalist policies, pro-natalist policies, guest workers, rural-urban migration, step migration, intervening obstacles, transnational migration, return migration, counterurbanization, suburbanization",
  "Unit 3: Cultural Patterns and Processes - culture, cultural traits, cultural diffusion, acculturation, assimilation, syncretism, cultural appropriation, folk culture, popular culture, language families, dialects, lingua franca, creole languages, pidgin languages, religion, universalizing religions, ethnic religions, secularism, sacred spaces, cultural landscapes, ethnic enclaves, cultural hearths, taboo, material culture, non-material culture, cultural relativism, ethnocentrism, cultural imperialism, cultural convergence, cultural divergence, cultural region, cultural realm, culture complex, culture system, artifact, mentifact, sociofact, cultural barriers, innovation adoption, globalization, placelessness, neolocalism, commodification, culture shock, language branch, language group, isogloss, extinct languages, revived languages, language isolates",
  "Unit 4: Political Patterns and Processes - state, nation, nation-state, stateless nation, multinational state, multistate nation, sovereignty, territoriality, boundaries, geometric boundaries, physical boundaries, cultural boundaries, antecedent boundaries, subsequent boundaries, superimposed boundaries, relic boundaries, boundary disputes, centripetal forces, centrifugal forces, devolution, supranationalism, United Nations, European Union, terrorism, irredentism, geopolitics, enclave, exclave, federal state, unitary state, microstates, city-states, colonialism, imperialism, heartland theory, rimland theory, organic theory, shatterbelt, buffer state, satellite state, gerrymandering, electoral geography, redistricting, reapportionment, separatism, balkanization, ethnic cleansing, annexation, demilitarized zone (DMZ), maritime boundaries, exclusive economic zone (EEZ), continental shelf, territorial waters, high seas, landlocked states",
  "Unit 5: Agriculture and Rural Land-Use - agriculture, agribusiness, subsistence agriculture, commercial agriculture, intensive farming, extensive farming, shifting cultivation, pastoral nomadism, transhumance, plantation agriculture, mixed crop and livestock farming, dairy farming, grain farming, Mediterranean agriculture, horticulture, aquaculture, Green Revolution, biotechnology, GMOs, sustainable agriculture, organic farming, agrarian, rural settlement patterns, Von Thünen model, monoculture, polyculture, crop rotation, slash-and-burn agriculture, terrace farming, intercropping, agroforestry, food security, food deserts, urban agriculture, community-supported agriculture (CSA), precision agriculture, vertical farming, hydroponics, agritourism, land tenure, cadastral system, metes and bounds, township and range, long-lot survey system, rural depopulation, farm subsidies, commodity chains, agricultural subsidies, fair trade, global food distribution networks",
  "Unit 6: Cities and Urban Land-Use - urbanization, megacities, metacities, world cities, rank-size rule, primate city, central place theory, urban models, concentric zone model, sector model, multiple nuclei model, urban realms model, Latin American city model, Southeast Asian city model, African city model, suburbanization, edge cities, exurbs, gentrification, urban sprawl, smart growth, new urbanism, zoning, redlining, blockbusting, urban renewal, public housing, sustainable cities, urban hierarchy, central business district (CBD), urban heat island, mixed-use development, brownfield sites, greenfield sites, infill development, transit-oriented development, walkability, livability, urban planning, garden cities, metropolitan area, metropolitan statistical area (MSA), micropolitan statistical area, urban primacy, suburban fringe, peri-urban areas, rural-urban fringe, decentralization, counterurbanization, urban decline, filtering, urban revitalization, urban infrastructure, slum, informal settlements",
  "Unit 7: Industrial and Economic Development Patterns and Processes - industrial revolution, industrialization, post-industrial economy, economic sectors (primary, secondary, tertiary, quaternary, quinary), Weber’s least cost theory, bulk-gaining industries, bulk-reducing industries, agglomeration, deglomeration, outsourcing, offshoring, just-in-time production, global supply chain, transnational corporations (TNCs), economic development, Gross Domestic Product (GDP), Gross National Income (GNI), Human Development Index (HDI), Rostow's stages of economic growth, dependency theory, world-systems theory, sustainable development, fair trade, microfinance, ecotourism, comparative advantage, economies of scale, import substitution, export processing zones (EPZs), special economic zones (SEZs), free trade zones, trade blocs, neoliberalism, structural adjustment programs, foreign direct investment (FDI), globalization, digital divide, knowledge economy, innovation, creative destruction, research and development (R&D), industrial parks, high-tech corridors, technopoles, service economy, blue-collar jobs, white-collar jobs, informal economy, formal economy, gig economy, labor market",
  "Unit 8: Services and Settlements - service sector, central business district (CBD), hinterland, threshold, range, market area, rank-size rule, primate city, gravity model, Christaller’s central place theory, retail services, business services, public services, consumer services, service economy, urban hierarchy, settlement patterns, dispersed settlement, nucleated settlement, clustered settlement, rural-urban fringe, commuter zone, urban network, globalization, service industries, tertiary sector, quaternary sector, quinary sector, knowledge-based services, financial services, healthcare services, education services, real estate services, information technology services, hospitality services, tourism services, entertainment services, professional services, government services, non-profit services, retail trade, wholesale trade, logistics, transportation services, telecommunication services, media services, personal services, repair and maintenance services, cultural services, recreational services, scientific services, technical services, administrative services, support services, utilities, public administration, social services, emergency services, defense services, international services, local services, urban services, rural services, service clusters, back-office functions, front-office functions, business process outsourcing (BPO), call centers",
]

export const cli = await CLI.create(subjectName, unitNames, config)
